version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    working_directory: ~/repihapi
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:3.0.0
      - image: circleci/mysql:8.0
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: repihapi_test
        command: --default-authentication-plugin=mysql_native_password
    environment:
      - RAILS_ENV: test
      - BUNDLE_JOBS: "4"
      - BUNDLE_RETRY: "3"
      - TEST_DB_HOST: "127.0.0.1"
      - TEST_DB_PASSWORD: ""
    working_directory: ~/repihapi
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
