version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
    working_directory: ~/repihapi
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: circleci/mysql:8.0
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: repihapi_test
        command: --default-authentication-plugin=mysql_native_password
    environment:
      - RAILS_ENV: test
      - BUNDLE_JOBS: "4"
      - BUNDLE_RETRY: "3"
      - TEST_DB_HOST: "127.0.0.1"
      - TEST_DB_PASSWORD: ""
    working_directory: ~/repihapi
    steps:
      - checkout
      - ruby/install-deps
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Execute webpack
          command: bundle exec bin/webpack
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run: heroku run bundle exec rails db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main