default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: repihapi_development

test:
  <<: *default
  database: repihapi_test

production:
  <<: *default
  database: repihapi_production
  username: repihapi
  password: <%= ENV['REPIHAPI_DATABASE_PASSWORD'] %>
