default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: repihapi_development

test:
  <<: *default
  database: repihapi_test
  password: <%= ENV.fetch('TEST_DB_PASSWORD') { 'password' } %>
  port: 3306
  host: <%= ENV.fetch('TEST_DB_HOST') { 'db' } %>

production:
  <<: *default
  database: repihapi_production
  username: root
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:hostname] %>
  socket: /var/lib/mysql/mysql.sock
